### ISSUE TITLE
Support for easybuild paths outside of the easybuild prefix.

### ISSUE THREAD

**Issue by dominikborkowski** [hpcugent/easybuild#105]
It would be great to have an officially sanctioned method for specifying locations for various easybuild locations to reside outside of the EASYBUILD_PREFIX, namely:
- EASYBUILD_SUBDIR_SOFTWARE
- EASYBUILD_SUBDIR_MODULES

It seems that absolute paths can be provided right now, but that's an unintended result. It would be nice to have this officially supported and preserved for the future.

Use case: ability to manage multiple instances of easybuild on shared storage. By collecting the easyconfig files generated by easybuild in /some/REPO_NAME/<cluster>, it's then easy to have them tracked in a single git repository (for all of your clusters). Same thing goes for the custom input easyconfigs, say ones used to override or augment the ones provided by easybuild. Then the resulting software could be placed in /some/software/<cluster>. In fact, this allows one to completely forgo the use of EASYBUILD_PREFIX. 

Not sure what would be the best method for accomplishing that. In a way, it would be nice to follow a standard convention and have these environment variables use the suffix 'PATH'; however, just leaving them the way they are right now would be sufficient.

**Comment by boegel** [comment]
support for `--installpath-modules` and `--installpath-software` is being added in https://github.com/hpcugent/easybuild-framework/pull/1258, which also adds a check to make sure the `subdir` options are supplied a relative path

**Comment by boegel** [comment]
Closing this, let's follow up in https://github.com/hpcugent/easybuild-framework/pull/1258
