### ISSUE TITLE
eb fails to download sources, wget succeeds

### ISSUE THREAD

**Issue by psauer55** [hpcugent/easybuild#115]
After setting the http_proxy and https_proxy environment variables, I was able to install EasyBuild 2.0 using the bootstrap script on a server running ScientificLinux 6 which is behind a corporate proxy. When I try to download and build, e.g. using the command

`eb $CFGS1/g/GCC/GCC-4.9.2-CLooG.eb -d -r`

I get the output 

```
== temporary log file in case of crash /tmp/eb-ZyXjPR/easybuild-FwVY0e.log
== resolving dependencies ...
== processing EasyBuild easyconfig /cm/shared/local/easybuild/software/EasyBuild/2.0.0/lib/python2.6/site-packages/easybuild_easyconfigs-2.0.0-py2.6.egg/easybuild/easyconfigs/g/GCC/GCC-4.9.2-CLooG.eb
== building and installing GCC/4.9.2-CLooG...
== fetching files...
```

and the program hangs. Looking into the log file, I can see this:

```
== 2015-04-21 17:53:14,176 main.filetools DEBUG Trying to download gcc-4.9.2.tar.bz2 from http://ftpmirror.gnu.org/gcc/gcc-4.9.2/gcc-4.9.2.tar.bz2 to /home/<user>/easybuild/sources/g/GCC/gcc-4.9.2.tar.bz2
== 2015-04-21 17:53:14,176 main.filetools DEBUG Using timeout of 10 seconds for initiating download
== 2015-04-21 17:53:14,176 main.filetools DEBUG Not creating existing path /home/psa2545/easybuild/sources/g/GCC
== 2015-04-21 17:53:17,423 main.filetools DEBUG response code for given url http://ftpmirror.gnu.org/gcc/gcc-4.9.2/gcc-4.9.2.tar.bz2: 200
== 2015-04-21 17:54:58,266 main.filetools WARNING IOError occurred while trying to download http://ftpmirror.gnu.org/gcc/gcc-4.9.2/gcc-4.9.2.tar.bz2 to /home/<user>/easybuild/sources/g/GCC/gcc-4.9.2.tar.bz2: timed out
== 2015-04-21 17:54:58,266 main.filetools INFO Attempt 1 of downloading http://ftpmirror.gnu.org/gcc/gcc-4.9.2/gcc-4.9.2.tar.bz2 to /home/<user>/easybuild/sources/g/GCC/gcc-4.9.2.tar.bz2 failed, trying again... 
== 2015-04-21 17:55:01,297 main.filetools DEBUG response code for given url http://ftpmirror.gnu.org/gcc/gcc-4.9.2/gcc-4.9.2.tar.bz2: 200
```

After Ctrl-C, the last few lines of the python stack trace are:

```
  self.fetch_sources(self.cfg['sources'], checksums=self.cfg['checksums'])
  File "/cm/shared/local/easybuild/software/EasyBuild/2.0.0/lib/python2.6/site-packages/easybuild_framework-2.0.0-py2.6.egg/easybuild/framework/easyblock.py", line 267, in fetch_sources
    path = self.obtain_file(source)
  File "/cm/shared/local/easybuild/software/EasyBuild/2.0.0/lib/python2.6/site-packages/easybuild_framework-2.0.0-py2.6.egg/easybuild/framework/easyblock.py", line 561, in obtain_file
    if download_file(filename, fullurl, targetpath):
  File "/cm/shared/local/easybuild/software/EasyBuild/2.0.0/lib/python2.6/site-packages/easybuild_framework-2.0.0-py2.6.egg/easybuild/tools/filetools.py", line 278, in download_file
    write_file(path, url_fd.read())
  File "/usr/lib64/python2.6/socket.py", line 354, in read
    data = self._sock.recv(rbufsize)
  File "/usr/lib64/python2.6/httplib.py", line 542, in read
    s = self.fp.read(amt)
  File "/usr/lib64/python2.6/socket.py", line 383, in read
    data = self._sock.recv(left)
```

I know that using easybuild behind a proxy was an issue in previous versions, but I was happy to read that this has been fixed for 2.0, and I was hoping I could avoid downloading the sources by hand. It's strange since the bootstrap script succeeded in downloading and also I can download the gcc *.tar.bz file using wget without problems. By the way, is there a way to get easybuild to print the list of files it wants to download, e.g. for piping to wget?

**Comment by boegel** [comment]
The warning in the log file seems to indicate the download is taking too long (the GCC tarball is fairly big, 86MB):

```
WARNING IOError occurred while trying to download http://... to ...: timed out
```

Can you try using the `--download-timeout` option to see whether specifying a longer timeout helps?

**Comment by psauer55** [comment]
Ok, thanks, I tried running build for zlib (much smaller) and at least the download part worked. However, when I run the following:
`eb $CFGS1/g/GCC/GCC-4.9.2-CLooG.eb --download-timeout=1000 -r`
I get the following error:

== 2015-04-21 18:37:34,195 main.EB_GCC INFO This is EasyBuild 2.0.0 (framework: 2.0.0, easyblocks: 2.0.0) on host bezavrdatmaster01.
== 2015-04-21 18:37:34,195 main.EB_GCC INFO This is easyblock EB_GCC from module easybuild.easyblocks.gcc (/cm/shared/local/easybuild/software/EasyBuild/2.0.0/lib/      python2.6/site-packages/easybuild_easyblocks-2.0.0-py2.6.egg/easybuild/easyblocks/g/gcc.pyc)
== 2015-04-21 18:37:34,195 main.EB_GCC INFO Build dir set to /home/<user>/easybuild/build/GCC/4.9.2/dummy-dummy-CLooG
== 2015-04-21 18:37:34,196 main.EB_GCC INFO Install dir set to /home/<user>/easybuild/software/GCC/4.9.2-CLooG
== 2015-04-21 18:37:34,196 main.EB_GCC INFO Init completed for application name GCC version 4.9.2
== 2015-04-21 18:37:34,196 main.easyblock INFO Obtained application instance of for GCC (easyblock: None)
== 2015-04-21 18:37:34,197 main.EB_GCC INFO building and installing GCC/4.9.2-CLooG...
== 2015-04-21 18:37:34,197 main.EB_GCC INFO fetching files...
== 2015-04-21 18:37:34,197 main.EB_GCC INFO Starting fetch step
== 2015-04-21 18:37:34,199 main.EB_GCC INFO Running method fetch_step part of step fetch
== 2015-04-21 18:37:34,199 main.EB_GCC WARNING Easyconfig does not specify an EasyBuild-version (key 'easybuild_version')! Assuming the latest version
== 2015-04-21 18:37:34,199 main.filetools INFO Command eb found at /cm/shared/local/easybuild/software/EasyBuild/2.0.0/bin/eb
== 2015-04-21 18:37:34,201 main.filetools ERROR EasyBuild crashed with an error (at easybuild/software/EasyBuild/2.0.0/lib/python2.6/site-packages/easybuild_framework-2.0.0-py2.6.egg/easybuild/tools/filetools.py:293 in download_file): Unexpected error occurred when trying to download http://ftpmirror.gnu.org/gcc/gcc-4.9.2/gcc-4.9.2.tar.bz2 to /home/<user>/easybuild/sources/g/GCC/gcc-4.9.2.tar.bz2: a float is required
== 2015-04-21 18:37:34,201 main.easyblock WARNING build failed (first 300 chars): EasyBuild crashed with an error (at easybuild/software/EasyBuild/2.0.0/lib/python2.6/  site-packages/easybuild_framework-2.0.0-py2.6.egg/easybuild/tools/filetools.py:293 in download_file): Unexpected error occurred when trying to download http://ftpmirror.gnu.org/gcc/gcc-4.9.2/gcc-4.9.2.tar.bz2 to /ho
== 2015-04-21 18:37:34,201 main.EB_GCC INFO Closing log for application name GCC version 4.9.2

am I using --download-timeout incorrectly?

**Comment by boegel** [comment]
Ah, right, you need a small patch to make `--download-timeout` work in EasyBuild v2.0, this is fixed in the upcoming v2.1, see https://github.com/hpcugent/easybuild-framework/pull/1242.

The only thing you need to change is https://github.com/hpcugent/easybuild-framework/pull/1242/files#diff-805aeb0dd32c2c101000d8785c70df95R189

**Comment by psauer55** [comment]
Ok, thanks, I can now use --download-timeout and it is now building after what seemed like a long time for downloading. I tried downloading via wget and I noticed that the download stalled at 99% for what seemed like quite a long time before terminating successfully. Also, I noticed there were some failed ftp downloads in the logs, so maybe that delayed things. The http downloads seem to complete quickly.

**Comment by boegel** [comment]
`eb` will iterate of a couple of URLs, because for GCC it needs to download a number of sources. It's not smart enough (yet) to pairs sources to source URLs.

@psauer55: if you consider the issue you were running into fixed by specifying a longer download timeout, please close this issue (we try to refrain from closing issues created by others ourselves).

**Comment by psauer55** [comment]
Great, thanks for your help, I'm closing this issue.
