### ISSUE TITLE
Replace dot "." with underscore in environment variables for software with "." in his name

### ISSUE THREAD

**Issue by jas02** [hpcugent/easybuild#152]
In case that I am building software that contains "." in name like MPI.NET, there is problem with loading such a module, because environment modules can't contain dot in the name of variable.

**Comment by boegel** [comment]
https://github.com/hpcugent/easybuild-framework/issues/new would be a better place to report this, since this needs to be fixed in the EB framework

this repo only contain the docs (and wrapper package for `easybuild` on PyPI)

**Comment by jas02** [comment]
OK, created as #1391 in easybuild-framework

**Comment by boegel** [comment]
https://github.com/hpcugent/easybuild-framework/issues/1391
