### ISSUE TITLE
readthedocs - default easyblock (deprecated)

### ISSUE THREAD

**Issue by JackPerdue** [hpcugent/easybuild#173]
At: https://easybuild.readthedocs.org/en/latest/Concepts_and_Terminology.html#easyblocks

" In case an easyblock specification is not provided and no (software-specific) easyblock matching the software name could be found, a fallback mechanism will resort to using the generic ConfigureMake easyblock, which implements the common configure / make / make install procedure."

That behaviour was deprecated in 2.x (2.0?).

**Comment by boegel** [comment]
Nice catch @JackPerdue, I'll get that sorted.

**Comment by boegel** [comment]
see #174
