### ISSUE TITLE
Request for user-defined module header addition

### ISSUE THREAD

**Issue by DirkdeDraak** [hpcugent/easybuild#186]
This is a request to be able to have a user-defined module header section.

We add a "source /path/to/hpcmodlogging.tcl" to our headers, in order to log all module usage via (TCL) modules.
Now I patch ./easybuild/tools/module_generator.py every time I updated to a new EasyBuild.

Something like:
```
--- ./easybuild/tools/module_generator.py.orig  2015-06-16 14:25:54.219589476 +0200
+++ ./easybuild/tools/module_generator.py       2015-06-16 14:26:22.075776469 +0200
@@ -165,6 +165,10 @@

         lines = [
             self.MODULE_HEADER.replace('%', '%%'),
+            "",
+            "# USER-DEFINED - START",
+            self.variables[userdefined_module_header],
+            "# USER-DEFINED - END",
+            "",
             "proc ModulesHelp { } {",
             "    puts stderr { %(description)s",
             "    }",
```

**Comment by boegel** [comment]
Very similar to the `--modules-footer` option we already support.

**Comment by boegel** [comment]
support for `--modules-header` configuration option implemented in https://github.com/hpcugent/easybuild-framework/pull/1558, let's follow up there
