### ISSUE TITLE
modaltsoftname use breaks dependency resolution

### ISSUE THREAD

**Issue by DirkdeDraak** [hpcugent/easybuild#189]
When using 'modaltsoftname' to name a module different from it's original EB derived name only the module with the modaltsoftname is created. That creates a problem with dependency resolution, while other EB files cannot find the original EB name, thus builds fail.

One suggestion is to create *both* the original softwarename and the modaltsoftname modulefiles via a symlink construction.
Only drawback would be that you have multiple names for the software to go by.
You could make dot-files of the original softwarename symlinks and for dependency resolution look for both the not-hidden and hidden variants of a module.

**Comment by boegel** [comment]
@DirkdeDraak: https://github.com/hpcugent/easybuild-framework would be a better location for this issue

this repository is mostly about the documentation, so if we leave this here, chances are it will be forgotten about...

**Comment by DirkdeDraak** [comment]
Re-issued per you suggestion.
https://github.com/hpcugent/easybuild-framework/issues/1556
