### ISSUE TITLE
Request for a --force-all for rebuilding all dependencies

### ISSUE THREAD

**Issue by DirkdeDraak** [hpcugent/easybuild#190]
When trying to rebuild an easyconfig and ALL of its dependencies there seems no simple way to rebuild all of its dependencies as well.
The -f only forces the .eb files supplied to be rebuilt.
This option is useful (for example) for building rpms (of already existing software) on other paths.
--force-all or --force-all-dependencies.

Suggestion from Kenneth:
One way is to collect all easyconfigs in a directory, and then use ```eb <dir> --force --robot```; EasyBuild will pick up all easyconfigs in the directory, and force the rebuild (taking dependencies into account, so in the right order).

My current solution:
Run ```eb i/intel-2016.01.eb -Dr``` and gathering all the dependencies and then replace the eb files on the commandline with all the dependencies.
I overload the eb command by a function in bash that takes care of this.
Maybe this can be done internally in EB?

**Comment by boegel** [comment]
That would be a useful feature indeed, and should be fairly easy to implement (we already have everything needed in place, cfr. `-D`).

@DirkdeDraak: https://github.com/hpcugent/easybuild-framework would be a better location for this issue, please move it there?

**Comment by DirkdeDraak** [comment]
Moved per your @boegel request.
https://github.com/hpcugent/easybuild-framework/issues/1557
