### ISSUE TITLE
how to disable installation of module when the package already installed in system-wide

### ISSUE THREAD

**Issue by jmbeuken** [hpcugent/easybuild#201]
Hi, 
( OS : ubuntu 15.10)

the package M4 1.4.17 is already installed in the system-wide…

buildbot@ubu:~$ dpkg --list | grep m4
ii  m4                                  1.4.17-4                        amd64        macro processing language

but, if you want install GCC 5.2 with easybuild :

buildbot@ubu:~$ eb GCC-5.2.0.eb -Dr
== temporary log file in case of crash /tmp/eb-C4oOPa/easybuild-acAcQ3.log
Dry run: printing build status of easyconfigs and dependencies
CFGS=/home/buildbot/.local/easybuild/software/EasyBuild/2.6.0/lib/python2.7/site-packages/easybuild_easyconfigs-2.6.0-py2.7.egg/easybuild/easyconfigs
 * [ ] $CFGS/m/M4/M4-1.4.17.eb (module: M4/1.4.17)
 * [ ] $CFGS/g/GCC/GCC-5.2.0.eb (module: GCC/5.2.0)
== Temporary log file(s) /tmp/eb-C4oOPa/easybuild-acAcQ3.log* have been removed.
== Temporary directory /tmp/eb-C4oOPa has been removed.

is it possible to disable the M4 module installation ?

it's a general question against already package installed in system-wide...

**Comment by boegel** [comment]
I think `--filter-deps` is what you're looking for: http://easybuild.readthedocs.org/en/latest/Manipulating_dependencies.html#filtering-out-dependencies-using-filter-deps

**Comment by jmbeuken** [comment]
it works ! 
thanks… there are so many options… ;-)
great tool… I continue...

**Comment by boegel** [comment]
If that answers your question, please close this issue.

**Comment by jmbeuken** [comment]
sorry not accustomed
thanks again...
