### ISSUE TITLE
module load in development instructions didn't work

### ISSUE THREAD

**Issue by ajdecon** [hpcugent/easybuild#202]
I just walked through the process for setting up a new development environment (yay!), and found a small bug in the instructions.

The [instructions](/hpcugent/easybuild/blob/master/docs/Installation_Alternative.rst) indicate that the EasyBuild-develop module should be in the `$INSTALL_PREFIX` directory following the installation:

````
...
bash install-EasyBuild-develop.sh GITHUB_USERNAME $INSTALL_PREFIX
# update $MODULEPATH via 'module use', and load the module
module use $INSTALL_PREFIX
module load EasyBuild-develop
````

But when I ran the script to set up the development environment, it placed the EasyBuild-develop module in `$INSTALL_PREFIX/modules`. With `INSTALL_PREFIX=/easybuild` on my VM:

````
[ajdecon@ip-10-0-0-45 ~]$ module use /easybuild
[ajdecon@ip-10-0-0-45 ~]$ module av EasyBuild-develop
[ajdecon@ip-10-0-0-45 ~]$ ls /easybuild
easybuild             easybuild-easyconfigs  easybuild-wiki                modules
easybuild-easyblocks  easybuild-framework    install-EasyBuild-develop.sh  vsc-base
[ajdecon@ip-10-0-0-45 ~]$ ls /easybuild/modules
EasyBuild-develop
[ajdecon@ip-10-0-0-45 ~]$ module av modules/EasyBuild-develop

---------------------------------------------------------- /easybuild ----------------------------------------------------------
modules/EasyBuild-develop
[ajdecon@ip-10-0-0-45 ~]$
````

Note that with `module use $INSTALL_PREFIX`, the available modules include all the modules in `easybuild-framework/test`:

````
[ajdecon@ip-10-0-0-45 ~]$ module av 2>&1 | head

---------------------------------- /easybuild ----------------------------------
easybuild-framework/test/framework/modules/ATLAS/3.8.4-gompi-1.1.0-no-OFED-LAPACK-3.4.0
easybuild-framework/test/framework/modules/BLACS/1.1-gompi-1.1.0-no-OFED
easybuild-framework/test/framework/modules/CategorizedHMNS/Compiler/GCC/4.7.2/mpi/OpenMPI/1.6.4
easybuild-framework/test/framework/modules/CategorizedHMNS/Compiler/GCC/4.7.2/system/hwloc/1.6.2
easybuild-framework/test/framework/modules/CategorizedHMNS/Core/compiler/GCC/4.7.2
easybuild-framework/test/framework/modules/CategorizedHMNS/Core/toolchain/gompi/1.4.10
easybuild-framework/test/framework/modules/CategorizedHMNS/Core/toolchain/goolf/1.4.10
easybuild-framework/test/framework/modules/CategorizedHMNS/MPI/GCC/4.7.2/OpenMPI/1.6.4/numlib/FFTW/3.3.3
[ajdecon@ip-10-0-0-45 ~]$
````

I'm not sure if this is the correct behavior... but I would guess not?  If these aren't intended to be in the `MODULEPATH` after a develop install, I think we should change:

````
module use $INSTALL_PREFIX
````

to

````
module use $INSTALL_PREFIX/modules
````

in the instructions.

Happy to submit a PR to that effect if I'm interpreting it correctly, or feel free to change it yourselves. :)

**Comment by boegel** [comment]
Thanks for reporting this @ajdecon, fixed in #203 (and also pushed to `master` version of the docs).

Welcome back to the wonderful world of EasyBuild! ;)
