### ISSUE TITLE
Could not find any module command, make sure one available in your $PATH.

### ISSUE THREAD

**Issue by andreas-h** [hpcugent/easybuild#207]
I'm working on Debian Testing/Stretch, and have installed the lmod package (version 5.8).  I then activated lmod by sourcing lmod's `init/profile` script.  When I try to install easybuild using the documented bootstrap, I run into an error:

    $ python bootstrap_eb.py ~/.local/easybuild
    [[INFO]] Installation prefix /home2/hilboll/.local/easybuild
    [[ERROR]] Could not find any module command, make sure one available in your $PATH.
    Known module commands are checked in order, and include: modulecmd, lmod, modulecmd.tcl
    Check the output of 'type module' to determine the location of the module command you are using.

In my setup, the `module` command is a function:

    $ type module
    module is a function
    module () 
    { 
        eval $($LMOD_CMD bash "$@");
        [ $? = 0 ] && eval $(${LMOD_SETTARG_CMD:-:} -s sh)
    }

Please advise on how to proceed ...

**Comment by boegel** [comment]
@andreas-h EasyBuild requires that either the `lmod` binary is available through `$PATH`, or that `$LMOD_CMD` is defined (which should be the case based on your `module` function?)

See also http://easybuild.readthedocs.org/en/latest/Installation.html#required-modules-tool .

Note that after installing EasyBuild, you'll need to configure it to use Lmod as a modules tool, rather than the default (environment modules), see http://easybuild.readthedocs.org/en/latest/Configuration.html#modules-tool-modules-tool (you can use `--modules-tool`, define `$EASYBUILD_MODULES_TOOL`, or specify `modules-tool` in a configuration file).

**Comment by andreas-h** [comment]
Thanks a lot!

**Comment by denwo1** [comment]
I still get this error with lmod is in my path:

$echo $PATH

echo $PATH 
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games::/usr/share/lmod/lmod:/usr/share/lmod/lmod::/usr/share/lmod/lmod/bin:/usr/share/lmod/lmod/usr/share/lmod/lmod::/usr/share/lmod/7.7/:/usr/share/lmod/7.7/:

**Comment by denwo1** [comment]
type module
bash: type: module: not found

type lmod
bash: type: lmod: not found

I have lmod installed I don't understand why it does not show up

**Comment by boegel** [comment]
@denwo1 What does `which lmod` give as result? You should add the location where the `lmod` binary is to $PATH, which is usually something like `.../lmod/libexec`.

Or, you should have `$LMOD_CMD` defined to the location of the `lmod` binary. If you just `source` the `init/bash` script that comes with Lmod, that should already be taken care of.

**Comment by denwo1** [comment]
Thanks you, lmod is recognized now, this link helped me also: https://github.com/easybuilders/easybuild/blob/master/docs/Installing-Lmod-without-root-permissions.rst

**Comment by denwo1** [comment]
Now when I try to install easybuild using the bootstrap I get this error: 
[[INFO]] installing EasyBuild with 'easy_install --quiet --upgrade --prefix=/tmp/tmpbdmMnb/eb_stage1 easybuild'
sh: 1: git: not found
[[ERROR]] Running 'easy_install --quiet --upgrade --prefix=/tmp/tmpbdmMnb/eb_stage1 easybuild' failed: error: Couldn't find a setup script in /tmp/easy_install-RPuC56/vsc-base-2.5.8/temp/easy_install-MllwQW/vsc-install.git

**Comment by boegel** [comment]
@denwo1 You need to have the `git` installed, see also https://github.com/easybuilders/easybuild-framework/issues/1962

**Comment by denwo1** [comment]
Indeed. Thanks you I finally install easybuild
