### ISSUE TITLE
NAMD support for OpenMPI & GCC (EB 2.5)

### ISSUE THREAD

**Issue by DanielTosello** [hpcugent/easybuild#225]
i'm attempting to build NAMD with OpenMPI & GCC under Easybuild 2.5 and i found the following issue...  a build arg (`-auto`) is passed to mpif90... this would be fine for intel fortran compilers but in this case it returns a fatal error as an unknown param & kills the build. 

Am i missing something? Is there a simple way of overriding this base param, short of extending the easyblock?

Here's my current `NAMD-2.10-gompi-2015a.eb` easyconfig file:
```
name = 'NAMD'
version = '2.10'
versionsuffix = '-mpi'

homepage = 'http://www.ks.uiuc.edu/Research/namd/'
description = """NAMD is a parallel molecular dynamics code designed for high-performance simulation of large biomolecular systems."""

toolchainopts = {'opt': True, 'pic': True, 'usempi': True}
toolchain = {'name': 'gompi', 'version': '2015a'}

namd_cfg_opts = '--tcl-prefix "/usr/local/easybuild/software/Tcl/8.6.3-GCC-4.9.2"'

sources = ['NAMD_%(version)s_Source.tar.gz']

dependencies = [
    ('Tcl', '8.6.3', '', ('GCC', '4.9.2')),
    ('FFTW', '3.3.4', '', ('gompi', '2015a'))
]

charm_arch = 'mpi-linux-x86_64'

moduleclass = 'chem'

```

**Comment by boegel** [comment]
@DanielTosello As far as I can tell, EasyBuild isn't specifying the `auto` anywhere, so it must be coming from NAMD itself?

EasyBuild is using `mpif90` rather than `gfortran` (by defining `$FC`, etc.) because `usempi` is set to `True` in `toolchainopts`.

If you set it to `False`, or remove the `, 'usempi': True` part since `False` is the default), it'll use `gfortran`...

**Comment by DanielTosello** [comment]
@boegel sorry for the delay in getting back to you on this, i intended to actually find where the flags are coming from and haven't had time.



I'm using the gompi, so... If i set `'usempi'` to false, charm++ fails like this: 

```
checking "whether build on MPI"... "yes"
checking "whether need to specify MPI library"... "yes"
checking "whether -lmpich"... "no"
checking "whether -lmpi"... "no"
Error: can not find mpi library
*** Please find detailed output in charmconfig.out ***
gmake[1]: *** [conv-autoconfig.h] Error 1
gmake[1]: Leaving directory `/usr/local/easybuild/build/NAMD/2.10/gompi-2015a-mpi/NAMD_2.10_Source/charm-6.6.1/mpi-linux-x86_64-gcc/tmp'
gmake: *** [headers] Error 2
```

Which i thought was expected behavior.

With it set to true, charm++ compilation fails like this: 

```
== 2016-06-08 15:42:43,546 runpy.run INFO parse_log_for_error msg: Command used: ./build charm++ mpi-linux-x86_64 mpicxx  --with-production -j16 -fPIC -O3 -march=native -DMPICH_IGNORE_CXX_SEEK
== 2016-06-08 15:42:43,546 runpy.run INFO parse_log_for_error (some may be harmless) regExp (?<![(,-]|\w)(?:error|segmentation fault|failed)(?![(,-]|\.?\w) found:
Error checking is disabled
gfortran: error: unrecognized command line option ‘-auto’
Fatal Error by charmc in directory /usr/local/easybuild/build/NAMD/2.10/gompi-2015a-mpi/NAMD_2.10_Source/charm-6.6.1/mpi-linux-x86_64-mpicxx/tmp
   Command mpif90 -auto -fPIC -I../bin/../include -DMPICH_IGNORE_CXX_SEEK -fPIC -O3 -march=native -O2 -c fmain.f90 -o fmain.o returned error code 1
gmake: [fmain-ok] Error 1 (ignored)
gmake: [fmain-ok] Error 1 (ignored)
gfortran: error: unrecognized command line option ‘-auto’
Fatal Error by charmc in directory /usr/local/easybuild/build/NAMD/2.10/gompi-2015a-mpi/NAMD_2.10_Source/charm-6.6.1/mpi-linux-x86_64-mpicxx/tmp
   Command mpif90 -auto -fPIC -I../bin/../include -DMPICH_IGNORE_CXX_SEEK -fPIC -O3 -march=native -O2 -c pup_f.f90 -o pup_f.o returned error code 1
gfortran: error: unrecognized command line option ‘-auto’

...etc
```

I'll add more info when i can, please let me know how i can help with this :)

**Comment by boegel** [comment]
@DanielTosello Please share the full log file (preferably with `--debug` enabled)?

I am seeing the `gfortran` errors on `-auto` not being recognised too when I use your easyconfig file, but they are actually ignored (since the `/build charm++ ...` command exits with `0`), and I also see this: 

```
charm++ built successfully
```

The actual problem seems to be something else. For me, it's because of this:

```
ERROR: No such directory /usr/local/easybuild/software/Tcl/8.6.3-GCC-4.9.2  
```

You should use this rather than hardcoding the path to the Tcl installation:

```
namd_cfg_opts = "--tcl-prefix $EBROOTTCL"
```

But if you got the path right, this won't solve the problem you are seeing.

**Comment by DanielTosello** [comment]
Thanks again for your help, @boegel, and sorry about the delay between responses here. 

I've run the process with --debug, and have also had our Intel licenses renewed (which was the blocker for building it with Intel compilers) and have seen a similar problem in both cases. Of course, i've also seen that charm++ does compile but `config` later fails.

I've attached my log output.

[easybuild-NAMD-2.10-20160622.160728.CSJJZ.log.txt](https://github.com/hpcugent/easybuild/files/327117/easybuild-NAMD-2.10-20160622.160728.CSJJZ.log.txt)

**Comment by boegel** [comment]
@DanielTosello sorry for not coming back to this, summer holidays...

Is this a problem for you, any progress?

**Comment by DanielTosello** [comment]
@boegel thanks for following up, sorry it took me a few days to get back to you. 

The problem in the logs above was embarrassingly easy to fix actually... we were missing csh and something in there relies on it for a shell call, which of course isn't actually accounted for in deps.

We have since worked through and have NAMD built with both the intel and gompi toolchains, but my coworker actually did the builds.

**Comment by boegel** [comment]
@DanielTosello OK, we can handle this by specifying `csh` as a required OS dependency... Does that makes sense?

**Comment by DanielTosello** [comment]
Sure does :) Thanks for your help, i've learned a lot about the EB system
doing this and hope i can make some contributions in the future.

**Comment by boegel** [comment]
`tcsh` as OS dep taken care of in https://github.com/hpcugent/easybuild-easyconfigs/pull/3491

@DanielTosello this is good to close now? Looking forward to further contributions from you!

**Comment by DanielTosello** [comment]
For this particular issue, this one is good to close.

Thanks for your help
--Daniel
