### ISSUE TITLE
Instalation error for Python (mpi4py download problem)

### ISSUE THREAD

**Issue by eediaz1987** [hpcugent/easybuild#231]
I am trying to install Python 2.7.9, using goolf-1.7.20 and foss2015a, and need a file called mpi4py.tar.gz, because my easybuild can't download from http://www.python.org/ftp/python/2.7.9/mpi4py-1.3.1.tar.gz was not found (HTTP response code 404), and from http://bitbucket.org/mpi4py/mpi4py/downloads/mpi4py-1.3.1.tar.gz timed out.
I need some help

**Comment by boegel** [comment]
@eediaz1987 Hmm, weird, https://bitbucket.org/mpi4py/mpi4py/downloads/mpi4py-1.3.1.tar.gz works fine for me... Try downloading from here: https://pypi.python.org/pypi/mpi4py/1.3.1 ?

**Comment by eediaz1987** [comment]
thanks, i think that the problem with https://bitbucket.org/mpi4py/mpi4py/downloads/mpi4py-1.3.1.tar.gz is my country, but i download from the last url that you give me
