### ISSUE TITLE
List of supported software and actual available EasyConfigs differ

### ISSUE THREAD

**Issue by SethosII** [hpcugent/easybuild#283]
The list of supported software and the actual available EasyConfigs don't match in all cases. An example is TopHat. The wiki says that only version 2.0.4 is available (http://easybuild.readthedocs.io/en/latest/version-specific/Supported_software.html#tophat) but when I search with `eb` or look at the EasyConfigs repository (https://github.com/hpcugent/easybuild-easyconfigs/tree/master/easybuild/easyconfigs/t/TopHat) there are a lot more versions available.

How do you generate the list of supported software and is there maybe an issue with detecting all the stuff?

**Comment by boegel** [comment]
@SethosII Hmm, this is supposed to be a one-on-one match, so something is definitely going wrong here...

We generate this page using `--list-software`, but clearly something went very wrong the last time we did this.

Did you run into any other examples, or did you only notice this for `TopHat`?

**Comment by boegel** [comment]
OK, there's definitely a weird bug in the `--list-software` implementation somewhere...

This works as expected:

```
$ eb --list-software=detailed | grep TopHat
* TopHat
TopHat is a fast splice junction mapper for RNA-Seq reads.
  * TopHat v2.0.4: goolf/1.4.10
  * TopHat v2.0.8: ictce/5.3.0
  * TopHat v2.0.8 (versionsuffix: '-biodeps-1.6-extended'): goolf/1.4.10, ictce/5.3.0
  * TopHat v2.0.10: ictce/5.5.0
  * TopHat v2.0.13: goolf/1.7.20
  * TopHat v2.0.14: goolf/1.7.20
  * TopHat v2.1.0: intel/2015b
  * TopHat v2.1.1: foss/2015b, foss/2016a
```

However, this is the corresponding output with `eb --list-software=detailed --output-format=rst`:

```
*TopHat*
++++++++

TopHat is a fast splice junction mapper for RNA-Seq reads.

*homepage*: http://ccb.jhu.edu/software/tophat/

==========    =========================    =================================
version       versionsuffix                toolchain                        
==========    =========================    =================================
``2.0.4``     ``-biodeps-1.6-extended``    ``goolf/1.4.10``                 
==========    =========================    =================================
```

I'll figure out what's wrong here, it probably has something to do with having a `versionsuffix` for some but not all entries...

Thanks for reporting this @SethosII!

**Comment by SethosII** [comment]
Hey @boegel, another example would be `Boost`. The latest version as of the wiki is 1.58 but `eb` also shows an EasyConfig for 1.61.

**Comment by boegel** [comment]
Bug is fixed in https://github.com/hpcugent/easybuild-framework/pull/2032, I will update the list of supported software later today with the release of EasyBuild v3.0.1 .

Thanks for reporting this @SethosII!
