### ISSUE TITLE
Easyblock documentation improvements

### ISSUE THREAD

**Issue by verdurin** [hpcugent/easybuild#324]
The `easyblock` documentation at http://easybuild.readthedocs.io/en/latest/Implementing-easyblocks.html appears to be lagging behind changes in the framework.

For instance, the `run_cmd` example is out of date.

**Comment by boegel** [comment]
@verdurin fixed in #325, anything else you noticed?

**Comment by verdurin** [comment]
That was the one I bumped against. 

Thanks.
