### ISSUE TITLE
Improve EasyBuild documentation, while moving it on ReadTheDocs

### ISSUE THREAD

**Issue by fgeorgatos** [hpcugent/easybuild#37]
Ref. https://easybuild.readthedocs.org/en/latest/

20141103
--------

* [x] add logo
* [x] move index.rst under ./docs
* [x] add a subdir ./docs/version-specific, with all related bits
* [x] add useful link: http://johnmacfarlane.net/pandoc/try/?text=%0A&from=markdown_github&to=rst
* [x] add useful link: http://rst.ninjs.org
* [x] use HPL as first example
* [x] Move section on `--try-*` features, in favor of Commonly Used command line options, yet not the WRF example
* [x] Consider using google analytics; update: yes, wanted
* [x] add in section to landing page (from gh-pages) + HUST'14 ref

20141104
--------

* [x] set up auto-triggering rebuild on push, on RTD
* [x] get rid of stale pages (either at fgeorgatos repo or wherever)
* [x] update homepage; gh-pages
* [x] review documentation in PDF form
* [x] mention conference calls @ hangouts
* [x] Fix sidebar TOC level; this is clearly dependent on the theme: default fixes it
* [x] Reference to primary software URL (homepage)!
* [x] update README
* [x] cleanup wiki

After_20141104
--------------

* [ ] Find ways to improve the PDF output,
* [ ] Finalize upon Lmod/5.8.0 vs Lmod/5.6.3
* [ ] Fix code-blocks rendering, pygments should kick-in with coloring, shouldn't it?
* [ ] For EasyBuild: add support for -a=rst logic; samewise for easyblocks, toolchains etc
* [ ] Consider (future) using pip requirements file, as means of adding in EasyBuild itself, so that it's exposed in $PYTHONPATH
* [ ] about custom module naming schemes (pick the git tree for existing file)
* [ ] consider adding a WRF.png with the dependencies on the homepage, to demonstrate the features

**Comment by fgeorgatos** [comment]
Hi, I think this issue should now be closed; possibly with migrating pending tasks to separate issue(s).

**Comment by boegel** [comment]
@fgeorgatos: up for doing that yourself? :)

**Comment by fgeorgatos** [comment]
done ;-)
