### ISSUE TITLE
document toolchainopts

### ISSUE THREAD

**Issue by boegel** [hpcugent/easybuild#66]
Document `toolchainopts` (once `--avail-toolchainopts` is supported), mention that they don't make sense in combination with a `dummy` toolchain

**Comment by ocaisa** [comment]
+1 for this

**Comment by pescobar** [comment]
I have arrived here looking for the documentation for toolchainopts  ;)

+2 for this

**Comment by boegel** [comment]
fixed in #1830, see e.g. `eb --avail-toolchain-opts intel` and http://easybuild.readthedocs.io/en/latest/version-specific/toolchain_opts.html
