### ISSUE TITLE
Hidden dependency issue

### ISSUE THREAD

**Issue by ebgregory** [hpcugent/easybuild#69]
(v 1.16.1)
When I use eb --force to install software with hidden dependencies easybuild does not find the hidden dependencies and installs them as *non-hidden* modules. 

As an example, I have an easyconfig file util-wrapper-1.0.eb (appended at the bottom) that only contains hidden dependencies (zlib, ncurses, binutils) and  installs nothing, using the Toolchain easyblock.

* If I first install zlib, ncurses and binutils separately by hand using ```eb --hidden``` then run 
```eb util-wrapper-1.0.eb```, it installs util-wrapper-1.0.eb as desired finding the hidden dependencies.

* If I *do not* first install the dependencies, Easybuild correctly installs them as hidden when I run ```eb util-wrapper-1.0.eb```.

* However if I then re-run the install with ```eb --force util-wrapper-1.0.eb```, then Easybuild re-installs the dependencies as non-hidden modules so in the module directory for the dependencies I have both hidden and non-hidden modules pointing to the same install directory.

Example easyconfig file util-wrapper-1.0.eb:

```
easyblock = 'Toolchain'

name = 'util-wrapper'
version = '1.0' 
homepage = 'http://nopage'

description = "A simple wrapper for utilities needed by compilers. Nothing is installed, but it     ensures the dependencies are loaded and available."

toolchain = {'name': 'dummy', 'version': 'dummy'} 

dependencies = [
		     ('zlib', '1.2.8'),
		     ('binutils', '2.24'),
		     ('ncurses', '5.9'),
		     ]		 


hiddendependencies = [
		     ('zlib', '1.2.8'),
		     ('binutils', '2.24'),
		     ('ncurses', '5.9'),
		     ]		 


moduleclass = 'tools'
```

**Comment by boegel** [comment]
@ebgregory: thanks for reporting this, you're definitely hitting a but here... Since this is clearly an issue with the interplay of --force with `hiddendependencies`, it's a framework issue, so please open a bug report via https://github.com/hpcugent/easybuild-framework/issues/new instead (and then close this issue).

**Comment by boegel** [comment]
moved to https://github.com/hpcugent/easybuild-framework/issues/1134
