### ISSUE TITLE
Can lua files be produced after build process?

### ISSUE THREAD

**Issue by ZAM-** [hpcugent/easybuild#76]
Is there an option to produce a lua file to be used with Lmod or is the tcl format the only option?

**Comment by boegel** [comment]
@ZAM-: for now, only generating Tcl module files is supported, but we hope to change that soon;

In a couple of weeks, the Lmod developer Robert McLay (@rtmclay) will be joining us at the next EasyBuild hackathon, where we can hopefully finish the work by @pforai on adding support for generating Lua module files, see https://github.com/hpcugent/easybuild-framework/pull/1060 .

I hope to get this in by EasyBuild v2.1 (so not the next release, but the one after that).

**Comment by ZAM-** [comment]
Awesome! I will be looking forward to the next couple releases. I will close this ticket. Keep up the great work!
