### ISSUE TITLE
Globally set configuration options.

### ISSUE THREAD

**Issue by ZAM-** [hpcugent/easybuild#77]
Is there a way to globally set the configuration options that you can manually set with the eb command? I'm sorry if these aren't necessarily issues as they are just questions =/

**Comment by boegel** [comment]
You can configure EasyBuild on three different levels: via configuration files, via environment variables, and via command line options to `eb`. See http://easybuild.readthedocs.org/en/latest/Configuration.html for all the details.

I don't mind you opening issues to ask questions, but let me propose two better alternatives: the EasyBuild mailing list, and the `#easybuild` IRC channel @ freenode.net, see also http://easybuild.readthedocs.org/en/latest/index.html#getting-help .
