### ISSUE TITLE
missing and/or incomplete documentation regarding environment variables

### ISSUE THREAD

**Issue by dominikborkowski** [hpcugent/easybuild#85]
It would be nice to have a documented mapping between the available options: command line, config and environment, and what their precedence is. For example a table mapping

--installpath | installpath | EASYBUILD_INSTALLPATH 
? | set-gid-bit | EASYBUILD_SET_GID_BIT

Or at least an explanation of used convention: do dashes in the config options always equal underscores in the environment variables? 

In addition, current install documentation on some pages mentions EASYBUILD_PREFIX and on other it refers to EASYBUILD_INSTALLPATH. It's a bit confusing, considering by default those seem to point to the same location: $HOME/.local/easybuild. 

Thanks!

**Comment by boegel** [comment]
Hi @dominikborkowski, thanks for opening this issue.

http://easybuild.readthedocs.org/en/latest/Configuration.html#supported-configuration-types already covers part of your question, but I guess the mapping from cmdline options to env vars and configfile entries could be made clearer.

Basically: env var is upper case of cmdline option, with `-` replaced by `_` and using `$EASYBUILD_` prefix; cfgfile entry is same name as cmdline option (long name), but without the `--` bit

**Comment by boegel** [comment]
The difference between `--prefix` and `--installpath` isn't clear, indeed.

Basically, `--prefix` also changes `--installpath` (not the other way around), and also affects the default value for `--buildpath`, `--sourcepath` and a couple of others.

I'll look into making this more clear in the documentation, thanks!

**Comment by boegel** [comment]
fixed with https://github.com/hpcugent/easybuild/pull/114
